import "~/styles/globals.css";

import { cookies } from "next/headers";
import { TRPCReactProvider } from "~/trpc/react";

import Navbar from "./_components/molecules/Navbar";
import Footer from "./_components/molecules/Footer";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-black">
        <div className="flex min-h-screen flex-col items-center gap-14 py-4 font-poppins md:gap-20">
          <Navbar />
          <TRPCReactProvider cookies={cookies().toString()}>
            {children}
          </TRPCReactProvider>
          <Footer />
        </div>
      </body>
    </html>
  );
}
